# Generated by Django 5.1.6 on 2026-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('badge_label', models.CharField(blank=True, help_text="Short tag shown on card, e.g. 'CEH v13', 'Masters'", max_length=60)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True, help_text='Verification / badge link')),
                ('description', models.TextField(blank=True)),
                ('certificate_image', models.ImageField(blank=True, help_text='Upload a certificate image (JPG/PNG/PDF preview)', null=True, upload_to='certificates/')),
                ('level', models.CharField(choices=[('expert', 'Expert / Top Tier'), ('professional', 'Professional'), ('associate', 'Associate'), ('beginner', 'Beginner / Foundation')], default='professional', max_length=20)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Pin to top and show a highlight glow')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first (0 = top)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['display_order', '-issue_date', '-created_at'],
            },
        ),
    ]
