# Generated by Django 5.1.6 on 2026-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="Second line of title, e.g. 'Secure Photo Journal'", max_length=200)),
                ('category', models.CharField(choices=[('dev', 'Full-Stack Development'), ('security', 'Cybersecurity'), ('ml', 'ML / Research'), ('research', 'Research'), ('other', 'Other')], default='dev', max_length=20)),
                ('section', models.CharField(choices=[('featured', 'Featured Work'), ('security', 'Cybersecurity Projects')], default='featured', help_text='Which section on the Projects page this appears in', max_length=20)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(blank=True, default='🚀', help_text='Emoji shown on small cards, e.g. 🛡️', max_length=10)),
                ('stat1_value', models.CharField(blank=True, help_text="e.g. '100%'", max_length=30)),
                ('stat1_label', models.CharField(blank=True, help_text="e.g. 'XSS / SQLi blocked'", max_length=60)),
                ('stat2_value', models.CharField(blank=True, help_text="e.g. '30%'", max_length=30)),
                ('stat2_label', models.CharField(blank=True, help_text="e.g. 'Faster request handling'", max_length=60)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, e.g. 'Python, Django, Nginx'", max_length=500)),
                ('live_url', models.URLField(blank=True, help_text='Live / demo link')),
                ('source_url', models.URLField(blank=True, help_text='GitHub / source link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('image_right', models.BooleanField(default=False, help_text='Featured card: put image on the right side')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show highlight glow / pin at top of its section')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first (0 = top)')),
                ('date_label', models.CharField(blank=True, help_text="Date shown on card, e.g. 'Mar 2026'", max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', 'section', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='certification',
            name='badge_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
