# Generated by Django 5.1.6 on 2026-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_alter_certification_badge_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_style',
            field=models.CharField(choices=[('long', 'Long Card — full layout with image panel'), ('short', 'Short Card — compact, no image panel')], default='long', help_text='How this project appears on the public Projects page', max_length=10),
        ),
    ]
